### ISSUE TITLE
Mentioning GLEIF as major use case for ACDC's

### ISSUE THREAD

**Issue by blelump** [trustoverip/tswg-acdc-specification-archived#10]
Hi Sam,

in the spec [intro](https://github.com/SmithSamuelM/Papers/blob/master/whitepapers/ACDC_Spec.md#introduction) you mention GLEIF as primary major use case for the proposed spec. Furthermore there are other mentions to VC's, DID's and so on.

1. Shall the spec favor one use case (GLEIF) specifically by explicitly mentioning it where it'll be primarily applied? The spec itself is definitely more than that and as `major use case` doesn't exclude other use cases, it somehow favor this one. Other than that the lifetime of the spec may be far beyond the aforementioned use case, therefore may not be valid anymore.
2. Shall the spec reflect to other existing techies like VC/DID as opposed to be an alternative approach, proposing it's own way to solve the underlying problem? The adoption of both (VC/DID) is unclear yet, therefore it's not known where and how it'll end up.

**Comment by SmithSamuelM** [comment]
1) The mention of GLEIF is not meant to favor it but to illustrate a major adoption use case. This provides informative context
2) Its not clear where the w3c VC spec will end up. Discussions of VC version 2.0 indicate a bigger tent approach. So I did not include that discussion in the ACDC spec itself as it is not so relevant to the spec. But given that most people who are interacting with ACDC have some familiarity with some version of the VC spec, pointing out differences is informative.

I am open to suggestions on how better to include informative versus normative information in the spec.
